### ISSUE TITLE
Pet animals provide an error messages and slow down render.

### ISSUE THREAD

**Issue by madmurdok** [badasintended/wthit#109]
### Describe the issue

**Minecraft version:**  1.18.1 Java edition 
**Mod version:**  4.5.1

Once I try to focus on domesticated animal like wolf or horse - I get this error.
It shows shortly in mod-window, and more information you can see in logs. It has started... several days ago. 

### Log output

https://gist.github.com/madmurdok/35b761be029726de69aee3d1ea8f74e5

**Comment by deirn** [comment]
Did you crack the game or something? The UUID should never be blank for legitimate users.

Disable the pet owner tooltip on the minecraft plugin for now, that should make it not throw an error.

**Comment by madmurdok** [comment]
No idea. Everything as usual... but I've got this error. 
I've found some similar errors in internet, but they were connected to server-sources...

**Comment by madmurdok** [comment]
It helps! Thanks a lot!

**Comment by deirn** [comment]
> No idea.

What launcher did you use?

**Comment by haykam821** [comment]
I can also reproduce this issue on the Fabric version of WTHIT 4.8.0.

**Comment by deirn** [comment]
@Shurayukii @SCPRedMage @haykam821
Can you guys test this version for me, as I don't have geyser server to test.

[wthit-local.zip](https://github.com/badasintended/wthit/files/8379052/wthit-local.zip)

**Comment by SCPRedMage** [comment]
Tested both Forge and Fabric, neither is showing the owner of animals I know are tamed by both Java and Bedrock players.

**Comment by deirn** [comment]
@SCPRedMage try this: [wthit-local.zip](https://github.com/badasintended/wthit/files/8403962/wthit-local.zip)

Also please post your log with that version.

**Comment by SCPRedMage** [comment]
[waila_errors.zip](https://github.com/badasintended/wthit/files/8413829/waila_errors.zip)

Still has the same behavior as before the bug was reported, frame rate tanks and has an error in the box. I've attached error logs for both versions, but it looks like they're the same.

I also went ahead and made a world with a small fenced in horse near world spawn tamed by my Bedrock account that can be used for testing; you can grab it here: https://www.dropbox.com/s/bj7utvmtdp3iuab/Bedrock%20Horse.zip?dl=0

**Comment by deirn** [comment]
For what it's worth, the issue is caused by Authlib not checking if the server returns an error, so I went ahead and make an issue to Mojang [here](https://bugs.mojang.com/browse/MC-249893).
