### ISSUE TITLE
WTHIT crashing MC Java 1.19 on launch

### ISSUE THREAD

**Issue by Phosphonothioic** [badasintended/wthit#149]
### Describe the issue

WIn 10
MC Java 1.19
Forge 41.0.91

"waila (waila) has failed to load correctly
java.lang.NoClassDefFoundError: 
net/minecraftforge/client/event/RenderGameOverlayEvent$Post"

### Log output

https://gist.github.com/Phosphonothioic/8bf044f0d88ac728825bb09b5950bc4c

**Comment by AnonymousHacker1279** [comment]
Forge introduced a massive render overhaul in 41.0.64, breaking most mods. The error you're getting is due to the `RenderGameOverlayEvent.Post` class being refactored. It is now `RenderGuiOverlayEvent.Post`.

deirn, you may find this auto-remapper helpful for the upgrade: https://gist.github.com/amadornes/cead90457e766f6d4294cb6b812f91dc

**Comment by deirn** [comment]
Yeah, I'm already aware of the issue, shouldn't be too bad for wthit, just a few event class renames.
