### ISSUE TITLE
Custom head support

### ISSUE THREAD

**Issue by sternschnaube** [badasintended/wthit#237]
![image](https://github.com/badasintended/wthit/assets/120551916/d70f3550-4b12-4c89-b369-effc6efcaf9b)
****

**Comment by deirn** [comment]
I assume you get the head from [Minecraft Heads](https://minecraft-heads.com/custom-heads/monsters/37706-creeper-skeleton-skull)?

The command that it gives doesn't store the head name of the block entity.
```mcfunction
give @p minecraft:player_head{display:{Name:"{\"text\":\"Creeper Skeleton Skull\"}"},SkullOwner:{Id:[I;257906651,-2018555868,-1417719731,-326173565],Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFjNzVmMzViZGRlMjRlY2RmNzUwYjE0YTUwNjc3NjhlODIzMGExNTRkNDk4Yjc4NjNhNTQ2N2Y3ZWExMTg0MSJ9fX0="}]}}} 1
```
This result the block to have this data: 
```js
{
  SkullOwner: {
    Id: [I; 257906651, -2018555868, -1417719731, -326173565], 
    Properties: {
      textures: [{
       Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFjNzVmMzViZGRlMjRlY2RmNzUwYjE0YTUwNjc3NjhlODIzMGExNTRkNDk4Yjc4NjNhNTQ2N2Y3ZWExMTg0MSJ9fX0="
      }]
    }
  }
}
```

If it instead also set the name inside `SkullOwner` then WTHIT can get it's name
```mcfunction
give @p minecraft:player_head{display:{Name:"{\"text\":\"Creeper Skeleton Skull\"}"},SkullOwner:{Id:[I;257906651,-2018555868,-1417719731,-326173565],Name:"Creeper Skeleton Skull",Properties:{textures:[{Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFjNzVmMzViZGRlMjRlY2RmNzUwYjE0YTUwNjc3NjhlODIzMGExNTRkNDk4Yjc4NjNhNTQ2N2Y3ZWExMTg0MSJ9fX0="}]}}} 1
```
```js
{
  SkullOwner: {
    Id: [I; 257906651, -2018555868, -1417719731, -326173565], 
    Properties: {
      textures: [{
       Value:"eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzFjNzVmMzViZGRlMjRlY2RmNzUwYjE0YTUwNjc3NjhlODIzMGExNTRkNDk4Yjc4NjNhNTQ2N2Y3ZWExMTg0MSJ9fX0="
      }]
    },
    Name: "Creeper Skeleton Skull"
  }
}
```
![image](https://github.com/badasintended/wthit/assets/21150434/118e54e9-7f96-4b8e-912a-71d6cf748879)
_(the head shows as steve on the current version, it's a bug that was fixed in d2b424d96f10f28adc5118f58fce2ff08152d4cd)_

Minecraft Heads' custom heads are also hard to identify for them to be special-cased. All of them seem to have different UUIDs. If all have the same then that would be easy to hide the "Player Head" text and replace it with the custom name.

In the end, this is more of Minecraft Heads' issue than WTHIT's.

**Comment by sternschnaube** [comment]
Thank you so much 😊

**Comment by deirn** [comment]
[Head Name Fix](https://modrinth.com/mod/headfix) seem to retain the head item name to the placed block, that might fix the naming issue.
