### ISSUE TITLE
Tooltip for Polymer / PolyDecorations

### ISSUE THREAD

**Issue by sternschnaube** [badasintended/wthit#264]
### Enhancement

![image](https://github.com/badasintended/wthit/assets/120551916/4ef7a311-6444-4e60-adaf-fbaad29f5cb6)

**Comment by deirn** [comment]
Pretty sure Polymer has built-in support with WTHIT. Do you have it on the client?

**Comment by sternschnaube** [comment]
Have it on the client, but it doesn't seems to work.

**Comment by deirn** [comment]
What version of Polymer do you use? Seems like the compatibility is only recently enabled for 1.20.6.

https://github.com/Patbox/polymer/commit/0c47528ba9584a196f6fed3f84f27981e3d8c11e

**Comment by sternschnaube** [comment]
Using the latest 1.20.6 build, which was published on Modrinth.

**Comment by deirn** [comment]
Can I get your latest.log? Paste it on https://gist.github.com/.

**Comment by sternschnaube** [comment]
I hope it's fine that I used pastebin.

https://pastebin.com/raw/ZBxyeczx

**Comment by Patbox** [comment]
I imagine it is caused by the barrier/structure void blocks being blacklisted. So they would need to be either removed or overriden (not sure if polymer can do that without mixins, as I'm not versed with the api)<https://github.com/badasintended/wthit/blob/a56174f0cb827f05791b5da8454b3126c0d088cf/src/pluginVanilla/java/mcp/mobius/waila/plugin/vanilla/WailaPluginVanilla.java#L240-L243>

**Comment by deirn** [comment]
Added API to remove things from the default blacklist. Also changed the the impl of the blacklist to be easily bypassed by plugins, I'll PR to Polymer soon.
